SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION fnGetCharMaxHP(@CharID INT)
RETURNS INT
AS
BEGIN
	DECLARE @maxHP INT
	SET @maxHP = (SELECT CharMaxHP FROM Characters WHERE (CharID = @CharID))
	RETURN @maxHP
END
