SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE dbo.spGenerateRandomQuestID 
@questID INT OUTPUT
AS
BEGIN
	SELECT @questID = (SELECT TOP 1 QuestID FROM Quests ORDER BY NEWID())
	RETURN @questID
END
